
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 27 11:45:07 ART 2014
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESERV_INT = 43;
  public static final int MULT = 19;
  public static final int ASSIG = 39;
  public static final int LOWER = 16;
  public static final int PARENIZQ = 24;
  public static final int CONTINUE = 4;
  public static final int INT = 45;
  public static final int PUNTOCOMA = 26;
  public static final int LOWEREQUAL = 13;
  public static final int FOR = 7;
  public static final int ASSIGSUB = 40;
  public static final int LLCER = 32;
  public static final int AND = 30;
  public static final int OR = 29;
  public static final int CLASS = 3;
  public static final int RESERV_FLOAT = 42;
  public static final int DIFFERENT = 23;
  public static final int PLUS = 17;
  public static final int IF = 8;
  public static final int ID = 35;
  public static final int CORCER = 34;
  public static final int EOF = 0;
  public static final int HIGHEREQUAL = 14;
  public static final int LLAB = 31;
  public static final int RETURN = 9;
  public static final int EQUAL = 22;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int COMA = 27;
  public static final int HIGHER = 15;
  public static final int MOD = 21;
  public static final int PARENDER = 25;
  public static final int BREAK = 2;
  public static final int EXTERNINVK = 41;
  public static final int VOID = 11;
  public static final int RESERV_BOOLEAN = 44;
  public static final int DIVI = 20;
  public static final int CORAB = 33;
  public static final int NEG = 28;
  public static final int ELSE = 5;
  public static final int WHILE = 12;
  public static final int FLOAT = 37;
  public static final int STRING = 36;
  public static final int FALSE = 6;
  public static final int SUB = 18;
  public static final int ASIGPLUS = 38;
}

